# Generated by Django 6.0 on 2025-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LIBRARIAN', 'Librarian'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
