# Generated by Django 6.0 on 2025-12-28 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_managementprofile_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LIBRARIAN', 'Librarian'), ('MEMBER', 'Member')], default='LIBRARIAN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managementprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managementrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
